IBM/ibm-generative-ai

src/genai/services/request_handler.py
**READY**
This PR adds the following header to all requests to the watsonx.ai service:
`x-request-origin: python-sdk/version`
- Outbound requests.
- Internal Request from API Dev Team. 
---
=> feat: adding python-sdk as a request origin header

pyproject.toml, src/genai/model.py
---
**READY**
This PR improves the visual experience of `generage_async` function with a tqdm progress bar. Currently users have to create a custom progress bar as part of a callback function, or in the body of a loop that reads/prints the results of generate_async to the terminal.
Source code changes were only made in **src/genai/model.py**. I added tqdm as dependency to the `pyproject.toml` file ( @onkarbhardwaj approved doing so).
This was an issue (#218) in the inner-source repo of the project that was created before the open-source deployment.  Check the image below for reference.
This is a visual improvement, it can be tested with the code example below:
```
import os
from dotenv import load_dotenv
from genai.model import Credentials, Model
from genai.schemas import GenerateParams, …
```
=> Progress bar for async_generate method

documentation/docs/source/rst_source/genai.exceptions.genai_exception.rst, documentation/docs/source/rst_source/genai.exceptions.rst
---
**READY**
Fixes some typos in the documentation referencing bam_exception, when it should be genai_exception.
- Docs
N/A
=> fix: resolving genai typo in some docs files

.github/workflows/integration-test.yml
---
**READY**
I'd not accounted for examples that require extensions to be installed when I pushed the integration test changes previously.
This PR adds the installation of the `all` group to resolve this.
- Integration test work flow
=> fix: installing extensions for integration tests

examples/user/grid_search_params.py, examples/user/prompt_csv_random_rows.py, examples/user/prompt_from_all_csv.py, examples/user/prompt_from_all_dataframe.py, examples/user/prompt_from_dataframe.py, examples/user/self-reflection.py, tests/test_generate_schema.py, tests/test_request_handler.py, tests/test_service_interface.py, tests/test_service_utils.py
---
**READY**
Updated examples that were using incompatible parameters with the greedy method.
User Examples. 
#58 
---
=> update greedy examples removing incompatible params

src/genai/schemas/models.py
---
**READY**
Added deprecation warning to the ModelType class, with simple example on how to migrate to string based model id within the warning.
`genai.schemas.models`
Closes #42 
Since ModelType is imported in the `__init__.py` file under `genai.schemas`, the warning will be thrown until we remove the ModelType file completely, even if the specific class is not imported by the user's example.
=> Deprecation warning for ModelType Class

GETTING_STARTED.md, examples/user/prompt_templating/watsonx-prompt-templating.py
**READY**
- Updated importing credentials from `genai.model` to `genai.credentials` from `GETTING_STARTED.md` and `watsonx-prompt-templating` example to avoid possible side effect in the future and user following a wrong pattern.
- `GETTING_STARTED.md`
- `examples/user/prompt_templating/watsonx-prompt-templating.py`
Closes: #121
---
=> doc: update wrong import class of credential

src/genai/schemas/generate_params.py
---
**READY**
When added the **min_length** in the schema, it stopped working and accepting stop sequence lists like `["\n", "###", "."`] .
error: 
```pydantic.error_wrappers.ValidationError: 1 validation error for GenerateParams
stop_sequences -> 0
ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
```
GenerateParams schemas
#141
=> update schema for stop_sequences generate param

src/genai/schemas/descriptions.py, src/genai/schemas/generate_params.py, tests/test_generate_schema.py
**READY**
Add `typical_p` optional parameter for generate.
Generate / Schema
Closes: #80
---
=> feat: add typical_p parameter

src/genai/prompt_pattern.py
---
READY
Adding escaping for back-slashes in re.sub() value.
prompt template creation
Closes: #83 
---
=> adding escapting of backslashes for re.sub value

src/genai/extensions/langchain/llm.py, tests/extensions/test_langchain.py
**READY**
Calling `async_generate` inside our LangChain LLM crashes once it is called in parallel (`genai.exceptions.genai_exception.GenAiException: Can't have two active async_generate_clients`)
LangChain
```python
import asyncio
import os
import dotenv
import uvicorn
from genai import Credentials
from genai.extensions.langchain import LangChainInterface
from genai.schemas import GenerateParams
dotenv.load_dotenv()
api_key = os.getenv("GENAI_KEY", None)
api_endpoint = os.getenv("GENAI_API", None)
async def get_result():
loop = asyncio.get_event_loop()
def evaluate():
llm = LangChainInterface(
model="google/flan-ul2",
credentials=Credentials(api_key, api_endpoint),
params=GenerateParams(
decoding_method="sample",
max_new_tokens=10,
min_new_tokens=1,
stream=False,
temperature=0.5, …
```
=> fix(langchain): revert async generate

.gitignore, README.md, examples/user/generate_with_moderation.py, examples/user/model_as_string.py, pyproject.toml, src/genai/credentials.py, src/genai/extensions/langchain/llm.py, src/genai/model.py, src/genai/routers/files.py, src/genai/routers/prompt_template.py, src/genai/routers/tunes.py, src/genai/schemas/descriptions.py, src/genai/schemas/generate_params.py, src/genai/schemas/responses.py, src/genai/services/async_generator.py, src/genai/services/request_handler.py, src/genai/services/service_interface.py, tests/extensions/test_langchain.py, tests/test_credentials.py
- Add moderations support; now you can retrieve HAP for generated requests
- Internally improve streaming processing (poor or unstable internet connection)
- Internally improve server response parsing and error handling
- Add a user-agent header to distinguish Python SDK on the API
- LangChain - correct handling of stop_sequences
- Correctly set versions of used dependencies (httpx / pyyaml)
- Prevents unexpected modifications to user's GenerateParams passed to the Model class
- Prevents unexpected errors when GenerateParams contains stream=True and generate (non-stream) version is called
- Remove API version from the custom API endpoint
=> Release 2023.09.25

src/genai/routers/tunes.py
---
**READY**
This fix sets the correct endpoint for `tune_methods` method.
TuneManager
Closes: #160
---
=> fix(tunes): use correct endpoint for tuning methods

examples/user/langchain_qa.py, src/genai/extensions/langchain/prompt.py, tests/extensions/test_langchain.py
---
**READY**
Fix the following warning, which occurs in a newer version of LangChain.
```
UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
```
None
---
=> fix(langchain): use namespace import for prompt template

EXTENSIONS.md, src/genai/extensions/langchain/llm.py, src/genai/schemas/descriptions.py, src/genai/schemas/generate_params.py, src/genai/schemas/responses.py, src/genai/utils/extensions.py, tests/extensions/test_langchain.py
---
**READY**
Add new generate input parameter `stop_sequence` and return options parameter `include_stop_sequence`.
Remove the `enforce_stop_tokens` function from LangChain as we want consistent behaviour across the whole project.
Generate, LangChain
Closes: #183
---
=> feat: add stop_sequence parameter, remove it from Langchain

src/genai/extensions/localserver/local_api_server.py, src/genai/model.py, tests/test_model.py
---
**READY**
Temporary solution which prevents throwing on `RATE_LIMIT` related errors retrieved from the API. This is temporary because in the near future API will not accept an array of inputs, but just one input per request.
Model - generate and generate_as_completed methods
Closes: #201
---
=> feat: handle concurrency limits for generate and generate_as_completed

src/genai/schemas/responses.py, tests/test_schema_validation.py
---
**READY**
When there is a new (yet unknown) field from the API, it triggers a warning in the SDK. 
This message is not fatal and is not intended for the end user.
=> chore: change logger level for non explicitly defined properties

src/genai/services/connection_manager.py, src/genai/services/request_handler.py, tests/test_concurrent.py
---
**READY**
Switch to custom retry http transporter instead of manual retries. Also, increase retry limits.
Generate/Tokenize Async
Backward contribute to: #147
---
=> feat: switch to custom retry http transporter instead of manual retries

examples/user/files.py, src/genai/routers/files.py, src/genai/schemas/responses.py, src/genai/services/file_manager.py
**READY**
Due to the wrong type for the file's `bytes` field, the validations fail and throw.
This PR fixes that and adds an example which also suits as a test case.
Files
=> fix(files): correct type and add test example

examples/dev/history-async.py, examples/dev/load_token_env.py, examples/user/model_as_string.py, examples/user/model_utils.py, src/genai/services/async_generator.py, src/genai/utils/http_utils.py, tests/assets/response_helper.py, tests/extensions/test_langchain.py, tests/test_concurrent.py, tests/test_generate_schema.py, tests/test_generate_service.py, tests/test_model.py, tests/test_model_async.py, tests/test_schema_validation.py, tests/test_service_interface.py, tests/test_service_interface_async.py, tests/test_token.py
**READY**
- Replace deprecated/renamed model `google/ul2` to it's newer version `google/flan-ul2`.
- Improve handling of errors in case of `async` processing -> logs the response body
Tests, Async Generate
=> fix: integration tests / async error logging

src/genai/exceptions/genai_exception.py, src/genai/services/async_generator.py, src/genai/utils/http_utils.py
Currently, we throw errors like this one,
```
GenAiException: Client error '400 Bad Request' for url 'https://workbench-api.res.ibm.com/v1/generate'
For more information check: https://httpstatuses.com/400
```
however, we want to throw errors which would explain the real cause, like this:
```
genai.exceptions.genai_exception.GenAiException: {"status_code":400,"error":"Bad Request","message":"Invalid argument or out of range","extensions":{"code":"INVALID_INPUT","state":null,"reason":"3 INVALID_ARGUMENT: input tokens (35000) plus prefix length (0) must be < 4096"}}
```
Note: this is for the `generate_async` method. 
For the `generate` method it works as expected without further changes
=> feat: improve response errors formatting

src/genai/prompt_pattern.py
Make a quick fix before releasing 2.0 to prevent users from accidentally creating thousands of templates.
=> fix: prevent duplicating template with same name

src/genai/_utils/async_executor.py, src/genai/_utils/http_client/retry_transport.py, src/genai/_utils/limiters/adjustable_semaphor.py, src/genai/_utils/limiters/base_limiter.py, src/genai/_utils/limiters/external_limiter.py, src/genai/_utils/limiters/shared_limiter.py, tests/unit/utils/limiters/test_adjustable_semaphor.py
- add missing handlers for error/success reporting
- fix the `retries` property in transport (allow 0)
- handle changing limits on `AsyncSemaphore` when no tasks are being processed
- set the initial limit to the number of remaining limits (not the maximal one)
- set limit to 1 in case of an error
=> fix: external limiter implementation

poetry.lock, src/genai/extensions/langchain/chat_llm.py, src/genai/extensions/langchain/llm.py, src/genai/extensions/langchain/utils.py
- Update LangChain
- Override LangChain's GenerationChunk classes to allow us to use a custom merging object strategy (in version 0.1.1, LangChain started to merge objects with their new utility function, which does not allow merging some types like `int` / `datetime`, which we use very often).
Ref: #273
=> feat(langchain): update core and related dependencies

src/genai/credentials.py
READY
The default api_endpoint is "https://bam-api.res.ibm.com", but even the small ".com" typo can be confusing to some why it's not working, and can easily get ignored while trying to find the issue
None, it's a documentation change
Directly created this PR, I will create an Issue for this.
=> typo: fix bam api url in documentation

examples/extensions/llama_index/llama_index_llm.py, poetry.lock, pyproject.toml, src/genai/extensions/llama_index/embeddings.py, src/genai/extensions/llama_index/llm.py, tests/integration/extensions/test_llama_index.py
Since `llama-index` version 0.1.0 has switched to monorepo architecture. This PR reflects such a change.
Ref: #330
=> feat(llama-index): migrate to v0.10.x

documentation/source/conf.py, external/sphinx_multiversion/README.md, external/sphinx_multiversion/setup.py, external/sphinx_multiversion/sphinx_multiversion/__init__.py, external/sphinx_multiversion/sphinx_multiversion/__main__.py, external/sphinx_multiversion/sphinx_multiversion/git.py, external/sphinx_multiversion/sphinx_multiversion/main.py, external/sphinx_multiversion/sphinx_multiversion/sphinx.py, poetry.lock, pyproject.toml
The current `sphinx-multiversion` library is no longer maintained and has severe flaws, which we were trying to tackle with various `hacks`. 
For instance, to retrieve a current version when the text generation is being run, we had to parse `version.json` in the parent directory. However, we recently discovered that this approach does not work when multiple documentation sources share the same tag; we cannot detect the current version.
Because the library is relatively small, I've made it a part of our repository and added necessary things.
=> docs: switch to sphinx-multiversion fork

README.md
Just a README change.
Ref: #338
=> Update watsonx SDK URL in README

src/genai/extensions/lm_eval/model.py, tests/integration/extensions/cassettes/test_lm_eval/TestLMEval.test_generate_until.yaml
**READY**
Made LM Eval wrapper compatible with LM EVAL Huggingface wrapper.
(in terms of default max_gen_tokens and truncation).
LM Eval wrapper
---
=> Fix GenAI LM Eval Model API to be compatible with LM Eval HF model API
