IBM/ibm-generative-ai

- README.md
---
READY
- Added public documentation link to README
- Added license badge with link to README
> Added public doc link and license badge to README.md

- src/genai/model.py
---
**READY**
See the description of the linked issue.
Model
Closes: #11 
---
> add accessors attribute to model class

- README.md
**READY**
Adds the following Build / Pypi badges to the readme:
[![Build & Test](https://github.com/IBM/ibm-generative-ai/actions/workflows/main.yml/badge.svg?branch=main)](https://github.com/IBM/ibm-generative-ai/actions/workflows/main.yml)
[![Integration Tests](https://github.com/IBM/ibm-generative-ai/actions/workflows/integration-test.yml/badge.svg)](https://github.com/IBM/ibm-generative-ai/actions/workflows/integration-test.yml)
- Readme
None.
---
> feat: adding status badges to readme

- .pre-commit-config.yaml
- pyproject.toml
---
**READY**
Updating a number of package dependency versions. Automated tests we running with the highest version of these libraries already, so increasing the minimum version to match.
The more important update is for pydantic which had an issue around typing in python 3.9 (https://github.com/pydantic/pydantic/issues/5821). Resolved in version 1.10.8.
- Package dependencies.
N/A
---
> chore: updating package versions

- README.md
- documentation/docs/source/index.rst
- documentation/docs/source/rst_source/local_server.rst
---
**READY**
Added sphinx documentation for running locally served models, and added subsection in readme for prerequisites.
Sphinx documentation, readme
Closes: #24 
---
> 24 local server docs

- README.md
- documentation/docs/source/rst_source/examples.rst
- examples/user/grid_search_params.py
- examples/user/grid_search_params_greeating.py
**READY**
- Fixed spellings on examples and `README.md`
- Added `api_endpoint` examples to `README.md`
Contributes to: #24
---
> docs: example spelling fix, added api_url to readme

- documentation/docs/source/rst_source/examples/async.examples.user.rst
- documentation/docs/source/rst_source/examples/examples.user.rst
- documentation/docs/source/rst_source/examples/extensions.user.rst
- documentation/docs/source/rst_source/examples/prompts.user.rst
**READY**
- Fixed wrong links on documentations
Contributes to: #24
---
> docs: updated links

- tests/integration/test_examples.py
---
**READY**
Removed async examples from integration testing
> Removed async examples from integration testing

- .github/workflows/python-publish.yml
- examples/user/grid_search_params.py
- examples/user/prompt_csv_random_rows.py
- examples/user/prompt_from_all_csv.py
- examples/user/prompt_from_all_dataframe.py
- examples/user/prompt_from_dataframe.py
- examples/user/self-reflection.py
- pyproject.toml
- src/genai/exceptions/genai_exception.py
- src/genai/services/async_generator.py
- tests/test_concurrent.py
- tests/test_generate_schema.py
- tests/test_request_handler.py
- tests/test_service_interface.py
- tests/test_service_utils.py
**READY**
- Keep compatible parameters for greedy decoding in the examples
- Change build process to build all the assets required
- More informative error messages.
> New Release

- pyproject.toml
---
**READY**
Fix pydantic version, compatibility with latest pydantic version (root validators) to be addressed in another issue.
toml files
> pydantic version fix

- pyproject.toml
Reverts IBM/ibm-generative-ai#68
> Revert "pydantic version fix"

- pyproject.toml
> Added author and pydantic update

- documentation/docs/source/rst_source/genai.schemas.rst
- examples/user/prompt_tuning/classification.py
- examples/user/prompt_tuning/summarization.py
Main back into develop
Long loop!
> Release v0.2.1  (#93)

- documentation/docs/source/rst_source/genai.schemas.files_params.rst
- documentation/docs/source/rst_source/genai.schemas.tunes_params.rst
**READY**
- Added missing schemas doc: Tunes and Files
Contributes to: #24
---
> docs: added missing files

- EXTENSIONS.md
- innersource.yaml
---
**READY**
We do not need the innersource.yaml file in the open source repo, so I deleted. Also, I found a broken link in the EXTENSIONS file. I fixed it.
---
> deleted innersour.yaml file as it is not needed int he open source repo

- GETTING_STARTED.md
- examples/user/model_utils.py
- examples/user/prompt_tuning/classification.py
- src/genai/model.py
- src/genai/schemas/responses.py
- src/genai/services/service_interface.py
- src/genai/services/tune_manager.py
- tests/assets/response_helper.py
- tests/test_model.py
---
**READY**
Methods to indicate if models are available, to list the models, and to get the info
Schema, Response, Model
---
> mode availability and list utils

- GETTING_STARTED.md
- examples/user/grid_search_params.py
- examples/user/prompt_templating/watsonx-prompt-templating.py
- src/genai/schemas/descriptions.py
- src/genai/schemas/files_params.py
- src/genai/schemas/generate_params.py
- src/genai/schemas/history_params.py
- src/genai/schemas/token_params.py
- src/genai/schemas/tunes_params.py
- tests/test_concurrent.py
- tests/test_generate_schema.py
---
**READY**
Making sure all changes in main are also known to develop to avoid commit issues down the line
> Release 2023.08.01 (#123)

- documentation/docs/source/rst_source/genai.prompt.quickstart.basics.rst
- examples/user/prompt-raw-string.py
- tests/assets/capital-qa-sub.txt
- tests/test_prompt_pattern.py
---
**READY**
Tests only
Closes: #124 
---
> chore: update examples

- README.md
---
**READY**
Mention the CLI project in the README.
> docs: mention CLI in README

- examples/dev/alter-http-communication.py
- src/genai/services/connection_manager.py
- src/genai/services/request_handler.py
- src/genai/services/service_interface.py
- src/genai/utils/http_provider.py
**READY**
This PR introduces support for passing custom parameters to the underlying HTTP client (`httpx` library).
All, but it is not a breaking change.
Closes: #113
---
> feat(http): allow override httpx options

- src/genai/schemas/generate_params.py
- tests/test_generate_schema.py
> fix(params): do not strip special characters

- examples/user/langchain_generate.py
- src/genai/exceptions/genai_exception.py
- src/genai/extensions/langchain/llm.py
- src/genai/model.py
- src/genai/services/async_generator.py
- tests/assets/response_helper.py
- tests/extensions/test_langchain.py
- tests/test_concurrent.py
---
**READY**
Add missing implementation for the `generate` method (currently, only `call` method is implemented, but it lacks the information about the generation)
LangChain
Closes: #155
---
> Langchain - generate method

- src/genai/services/request_handler.py
> feat: add user-agent header

- src/genai/credentials.py
- src/genai/services/service_interface.py
- tests/test_credentials.py
Refs: IBM#160
---
**READY**
Remove version from api endpoint and handle it by sdk itself .
---
> feat(credentials): drop API version prefix from the endpoint

- src/genai/model.py
**READY**
Set the `stream` parameter based on the used method.
Model
Closes: #162
---
> fix: automatically set stream parameter based on the used method

- src/genai/routers/files.py
- src/genai/routers/prompt_template.py
- src/genai/routers/tunes.py
Refs: IBM#160
---
**READY/IN DEVELOPMENT/HOLD**
---
> fix: add version to all endpoionts 

- src/genai/extensions/langchain/llm.py
- tests/extensions/test_langchain.py
---
**READY**
LangChain
Closes: #167
---
> fix(langchain): escape stop_sequences

- examples/user/generate_with_moderation.py
- examples/user/model_as_string.py
- pyproject.toml
- src/genai/model.py
- src/genai/schemas/descriptions.py
- src/genai/schemas/generate_params.py
- src/genai/schemas/responses.py
- src/genai/services/async_generator.py
- src/genai/services/request_handler.py
- tests/extensions/test_langchain.py
**READY**
Model (generate), streaming in general
Closes: #145
---
> feat: add moderations support

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- CONTRIBUTING.md
- README.md
**READY**
Having an additional branch (`develop`) brings more cons than pros.
> chore: remove develop branch, update configs

- src/genai/services/async_generator.py
- src/genai/utils/errors.py
---
**READY**
`generate_async` and `tokenize_async`
Closes: #180
---
> feat(generate): cleanup async generator on termination

- documentation/docs/source/rst_source/examples/extensions.user.rst
- examples/user/huggingface_agent.py
- pyproject.toml
- src/genai/extensions/huggingface/__init__.py
- src/genai/extensions/huggingface/agent.py
- src/genai/extensions/langchain/llm.py
- src/genai/utils/extensions.py
- tests/extensions/test_huggingface_agent.py
> feat(huggingface): create a transformer agent extension 

- examples/dev/async-flaky-responses-ordered.py
- src/genai/credentials.py
- src/genai/extensions/langchain/prompt.py
- src/genai/extensions/localserver/local_api_server.py
- src/genai/extensions/pandas/prompt_sub.py
- src/genai/metadata.py
- src/genai/model.py
- src/genai/prompt_pattern.py
- src/genai/routers/files.py
- src/genai/routers/prompt_template.py
- src/genai/routers/tunes.py
- src/genai/schemas/descriptions.py
- src/genai/schemas/responses.py
- src/genai/services/async_generator.py
- src/genai/services/file_manager.py
- src/genai/services/prompt_template_manager.py
- src/genai/services/request_handler.py
- src/genai/services/service_interface.py
- src/genai/services/tune_manager.py
- src/genai/utils/json_utils.py
- src/genai/utils/watsonx_helpers.py
- tests/test_prompt_pattern.py
---
**READY**
Closes #191 
---
> fix: remove some typing errors

- src/genai/services/async_generator.py
---
**READY**
In the current version (0.3.0) calling `generate_async` from main thread works fine, however calling it from another thread or process raises the following errors:
```
genai_exception.py 33: signal only works in main thread of the main interpreter
genai_exception.py 33: Can't have two active async_generate_clients 
```
> fix: register signals only on the main thread

- src/genai/services/async_generator.py
- tests/conftest.py
- tests/test_model_async.py
---
**READY**
Fix `generate_async` hanging on `task.exception()`
Fix `max_concurrency_limit` + add a test case
Add `LIMITS_CHECK_SLEEP_DURATION` static property.
Async Generate, Async Tokenize
Closes: #199
---
> fix: prevent async processing hanging, fix max_concurrency_limit

- src/genai/extensions/huggingface/agent.py
- src/genai/extensions/langchain/llm.py
- src/genai/model.py
- src/genai/utils/general.py
- tests/test_model.py
- tests/test_utils.py
---
**READY**
Current parsing logic for `GenerateParams` is not bulletproof. This PR improves it and add some test cases.
> chore: improve parsing pydantic models

- GETTING_STARTED.md
- examples/dev/history-async.py
- examples/dev/load_token_env.py
- examples/user/grid_search_params.py
- examples/user/grid_search_params_greeating.py
- src/genai/extensions/localserver/local_api_server.py
- tests/test_credentials.py
- tests/test_service_utils.py
---
**READY**
- test credentials deprecation warning
- remove deprecated v1 prefix from api endpoint (local server extension)
Server
---
> chore: credentials related updates

- src/genai/services/async_generator.py
- tests/test_model_async.py
---
**READY**
Correctly handling errors and user abortion (SIGTERM / SIGINT).
In case of an error, the current batch is processed and other tasks are skipped.
Add test cases.
Related to: #180 
---
> fix: correctly handle async errors and process abortion

- .pre-commit-config.yaml
- examples/user/langchain_qa.py
- pyproject.toml
- src/genai/extensions/langchain/llm.py
- src/genai/extensions/localserver/local_api_server.py
- src/genai/model.py
- src/genai/schemas/files_params.py
- src/genai/schemas/generate_params.py
- src/genai/schemas/history_params.py
- src/genai/schemas/responses.py
- src/genai/schemas/token_params.py
- src/genai/schemas/tunes_params.py
- src/genai/utils/general.py
- src/genai/utils/request_utils.py
- tests/assets/response_helper.py
- tests/extensions/test_langchain.py
- tests/test_prompt_pattern_watsonx.py
- tests/test_prompt_template_manager.py
- tests/test_request_handler.py
---
**HOLD**
Migrate to Pydantic v2
All
Closes: #67
---
> feat: migrate to pydantic v2

- src/genai/model.py
---
**READY**
The standard/default `tqdm` mode on different environments (`jupyter` / `std` / `ui`) does not work as smoothly as one may except. Switching to `auto` mode should solve this.
https://tqdm.github.io/docs/shortcuts/#tqdmauto
`async_generate` method
> feat(tqdm): use auto mode

- examples/user/langchain_qa.py
Based on https://python.langchain.com/docs/modules/chains/foundational/sequential_chains#legacy-sequentialchain, the sequential chains are becoming deprecated and are being replaced by the LCEL.
> chore(langchain): replace sequential chain with LCEL

- src/genai/metadata.py
- src/genai/model.py
- src/genai/services/file_manager.py
- src/genai/services/prompt_template_manager.py
- src/genai/services/tune_manager.py
- src/genai/utils/request_utils.py
- tests/extensions/test_huggingface_agent.py
- tests/extensions/test_langchain.py
- tests/test_concurrent.py
- tests/test_files.py
- tests/test_generate_service.py
- tests/test_history.py
- tests/test_json_utils.py
- tests/test_metadata.py
- tests/test_model.py
- tests/test_model_async.py
- tests/test_prompt_pattern_watsonx.py
- tests/test_prompt_template_manager.py
- tests/test_request_handler.py
- tests/test_service_interface.py
- tests/test_service_interface_async.py
- tests/test_service_utils.py
- tests/test_token.py
- tests/test_tunes.py
- tests/test_utils.py
- tests/utils.py
---
**READY**
Refactored tests: api requests are mocked instead of method return values.
Closes: #208
> refactor: mock responses with pytest_httpx

- examples/user/langchain_serialization.py
- src/genai/credentials.py
- src/genai/extensions/langchain/chat_llm.py
- src/genai/extensions/langchain/llm.py
- src/genai/extensions/langchain/utils.py
- src/genai/extensions/localserver/local_api_server.py
> feat(langchain): make models serializable

- src/genai/schemas/descriptions.py
- src/genai/schemas/generate_params.py
- src/genai/schemas/responses.py
> feat(moderation): add support for more models

- src/genai/exceptions/genai_exception.py
- src/genai/schemas/responses.py
- src/genai/services/request_handler.py
- Handle cases where we receive an error during streaming
- Correctly parses API errors
> feat: improve error handling

- src/genai/model.py
---
**READY**
This functionally is repeating in the code, maybe we should handle it in the future universally.
> feat(tokenize): add rate-limit awareness to model.tokenize

- documentation/docs/source/rst_source/examples/extensions.user.rst
- examples/user/llama_index_llm.py
- pyproject.toml
- src/genai/extensions/common/utils.py
- src/genai/extensions/langchain/chat_llm.py
- src/genai/extensions/langchain/llm.py
- src/genai/extensions/langchain/utils.py
- src/genai/extensions/llama_index/__init__.py
- src/genai/extensions/llama_index/llm.py
- tests/extensions/test_langchain_chat.py
- tests/extensions/test_llama_index.py
**READY**
Right now we support only the standard llm. In the future agent, embedding... could be added.
#223
> feat(extensions): add support for llamaindex

- examples/user/llama_index_llm.py
- pyproject.toml
- src/genai/extensions/llama_index/llm.py
- tests/extensions/test_llama_index.py
---
**READY**
New versions of llamaindex changes imports (https://github.com/run-llama/llama_index/pull/9388)
> fix: correct llama-index import for new version

- examples/user/huggingface_agent.py
---
**READY**
**Fixing integration tests:** 
The huggingface example wanted to generate audio with uninstalled library which is not necessary.
> fix(examples): correct Hugging Face example prompt

- examples/extensions/langchain/langchain_chat_generate.py
- examples/extensions/langchain/langchain_chat_stream.py
- examples/extensions/langchain/langchain_generate.py
- examples/extensions/langchain/langchain_qa.py
- poetry.lock
- pyproject.toml
- src/genai/extensions/langchain/chat_llm.py
- src/genai/extensions/langchain/llm.py
- tests/integration/extensions/test_langchain.py
- tests/integration/extensions/test_langchain_chat.py
> feat: migrate to langchain_core

- examples/prompt/prompt.py
Update the `prompt` example to reveal the `list` method
> docs: update prompt usage example

- examples/system_prompt/__init__.py
- examples/system_prompt/system_prompt.py
- scripts/types_generator/schema_aliases.yaml
- src/genai/_generated/api.py
- src/genai/_generated/endpoints.py
- src/genai/_utils/service/base_service.py
- src/genai/client.py
- src/genai/system_prompt/__init__.py
- src/genai/system_prompt/schema.py
- src/genai/system_prompt/system_prompt_service.py
- tests/integration/system_prompt/cassettes/test_prompt_service/TestSystemPromptService.test_create_delete_system_prompt.yaml
- tests/integration/system_prompt/cassettes/test_system_prompt_service/TestSystemPromptService.test_create_delete_system_prompt.yaml
- tests/integration/system_prompt/test_system_prompt_service.py
> feat(system-prompts): init module

- examples/extensions/langchain/langchain_generate_with_template.py
- src/genai/extensions/_common/utils.py
- src/genai/extensions/langchain/chat_llm.py
- src/genai/extensions/langchain/llm.py
- correctly handles prompt_id and model_id (+ add example)
- accepts dictionaries in addition to Pydantic models
Ref: #285
> fix/feat: langchain templates and models

- examples/extensions/localserver/local_server.py
- examples/extra/logging_example.py
- examples/prompt/prompt.py
- examples/text/moderation.py
- examples/tune/tune.py
- tests/e2e/test_examples.py
> refactor: remove list comprehensions to preserve type-hints

- README.md
---
**READY/IN DEVELOPMENT/HOLD**
READY
Fix typo in the link URL to ibm-generative-ai-node-sdk
No
---
> fix: correct typo in url

- poetry.lock
- scripts/types_generator/extractor.py
- scripts/types_generator/schema_transformer.py
- Update dependencies 
- Because of updates, handle dates extraction
- Add support for handling `-` (minus character) in path name
> feat: improve types generation

- src/genai/_utils/http_client/httpx_client.py
- src/genai/_utils/http_client/retry_transport.py
- src/genai/_utils/responses.py
- src/genai/exceptions.py
- src/genai/text/embedding/embedding_service.py
- src/genai/text/generation/generation_service.py
- fix serialization in `multiprocessing` by implementing `__reduce__`
- handle non API response error in limiters
- generally improve error handling
> fix: improve http error handling

- examples/text/generation.py
- examples/text/simple_generation.py
> docs: add simple text generation example

- examples/text/generation_streaming.py
---
**READY**
Typo in an example that appears in the documentation.
Example
---
> Typo in example: speach -> speech

- examples/extensions/huggingface/huggingface_agent.py
The default tool in hugging-face - text-downloader is not working so I replaced it with custom run to avoid the error in tests.
> fix(huggingface): fix not working default tool

- examples/extensions/huggingface/huggingface_agent.py
- examples/extensions/langchain/langchain_agent.py
- examples/extensions/langchain/langchain_chat_generate.py
- examples/extensions/langchain/langchain_chat_stream.py
- examples/extensions/langchain/langchain_sql_agent.py
- examples/extensions/llama_index/llama_index_llm.py
- examples/text/chat.py
- src/genai/extensions/langchain/chat_llm.py
- src/genai/extensions/langchain/llm.py
- src/genai/text/chat/chat_generation_service.py
- tests/integration/extensions/cassettes/test_huggingface_agent/TestHuggingfaceAgent.test_agent.yaml
- tests/integration/extensions/cassettes/test_langchain_chat/TestLangChainChat.test_async_generate.yaml
- tests/integration/extensions/cassettes/test_langchain_chat/TestLangChainChat.test_generate.yaml
- tests/integration/extensions/test_langchain_chat.py
- tests/integration/text/cassettes/test_chat_service/TestChatService.test_create_history.yaml
- tests/integration/text/cassettes/test_chat_service/TestChatService.test_create_stream.yaml
- tests/integration/text/test_chat_service.py
Rename llama model + updating cassettes
> feat: new llama model
